Lazy load commands
vtex/findhelp pull request #6
Opened 2016-10-07 19:58 UTC by tamorim

This PR adds lazy load capability through the `module` property.

2016-10-10 22:31 UTC, vibegui requested changes
Awesome first iteration!!!

2016-10-10 22:31 UTC, firstdoit commented on src/finder.js
> +} from 'ramda'
Nice :joy:

2016-10-10 22:31 UTC, firstdoit commented on src/finder.js
> +  return type(node) === 'Object' && any(v => isCommand(v) || isModule(v), values(node)) && node
I feel that `v => isCommand(v) || isModule(v)` is *asking* to be *ramda'ed*, but I couldn't find a nice way to do it. 😁

2016-10-10 22:31 UTC, firstdoit commented on src/finder.js
> +  return require(node.module).default
I'd add compatibility for non-babel/ES6 modules (e.g `return require(node.module).default || require(node.module)`)

2016-10-10 22:31 UTC, firstdoit commented on src/finder.js
> +  if (isModule(next)) {
Why not encapsulate this inside `findNext`?

2016-10-10 22:31 UTC, firstdoit commented on src/finder.js
> +  const cmd = isModule(command) ? loadModule(command) : command
When have you felt that the client of `run` would send an *unrequired* module?

2016-10-10 22:31 UTC, firstdoit commented on src/helper.js
> +  return mapObjIndexed(n => isModule(n) ? loadModule(n) : n)(tree)
Unnecessary double-call, use parens and comma instead? :)

2016-10-10 22:31 UTC, firstdoit commented on src/helper.js
> +  return mapObjIndexed(n => fromPairs(n))(pairs)
`n => fromPairs(n)` === `fromPairs`? Also, double call!

2016-10-10 22:31 UTC, firstdoit commented on src/helper.js
> +  )(toPairs(tree))
Can you expand (maybe also add comments) on the necessity of converting to pairs?

2016-10-10 23:06 UTC, tamorim commented
@firstdoit Done!

2016-10-11 14:35 UTC, firstdoit commented
For future reference, avoid push force after a review, because GitHub apparently gets lost :P

2016-10-11 16:30 UTC, tamorim commented
@firstdoit Noted.

2016-10-11 18:02 UTC, tamorim commented
@firstdoit Latest optimizations on `helper` are done! Thank you for the extra brain on the refactor :+1:

2016-10-11 18:13 UTC, firstdoit commented
Thanks for letting me!

2016-10-11 18:20 UTC, firstdoit commented
![maravilhoso](https://cloud.githubusercontent.com/assets/1633518/19282833/32ae9d5c-8fc6-11e6-9074-3456a2d80f18.jpeg)

2016-10-11 18:20 UTC, vibegui approved these changes
LGTM!

2016-10-11 18:22 UTC, merged